# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ximin's Blog
subtitle: JFF
description: a simple, totally just for fun blog
keywords:
author: Ximin Lin
language: 
timezone: ''

# # hexo-generator-i18n
# # 需修改Hexo默认的空值为确切的语言列表，记得在主题languages目录下添加对应的语言.yml文件
# language: [zh,en]
# # hexo-generator-i18n 选项（可选，默认使用如下设置）
# i18n:
#   type: [page, post]
#   generator: [index, archive, category, tag]


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://ximinlin.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true # store images whatnot inside this folder
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page


# Gallery
gallery_dir: /gallery-images

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: massively
# theme: landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/XiminLin/ximinlin.github.io
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# # Hexo-renderer Marked
# marked:
#   gfm: true
#   pedantic: false
#   breaks: true
#   smartLists: true
#   smartypants: true
#   quotes: '“”‘’'
#   modifyAnchors: 0
#   anchorAlias: false
#   autolink: true
#   mangle: true
#   sanitizeUrl: false
#   headerIds: true
#   lazyload: true
#   prependRoot: true
#   postAsset: true
#   external_link:
#     enable: false
#     exclude: []
#     nofollow: false
#   disableNunjucks: false
#   descriptionLists: true


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-attrs
  anchors:
    level: 3
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: '#'


contact:
  address: 福建省福州市鼓楼区冶山路26号海洋社区
  phone: (+86) 130-5590-3386
  email: ximin.lin.work@outlook.com



navigation:
  home:
    link: /home/
  blog:
    name: blog
    link: categories/blog/
  project:
    name: project
    link: categories/project/
  resume: 
    link: /resume/
  galleries:
    link: /galleries/

